name: Test
permissions:
  contents: read
  pull-requests: write

on:
  push:
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Lint
        run: deno lint

      - name: Run Tests
        run: |
          deno test --unstable --allow-read --allow-net

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build Project
        run: |
          deno bundle src/index.ts dist/bundle.js
